// Altering Internally
export const ADD_INGREDIENT = "ADD_INGREDIENT"
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT"

// From Database
   // BURGER BUILDER
export const INIT_INGREDIENTS  = "INIT_INGREDIENTS"
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED"
   // ORDER SUBMIT
export const SUBMIT_START = "SUBMIT_START"
export const SUBMIT_SUCCESS = "SUBMIT_SUCCESS"
export const SUBMIT_FAILURE = "SUBMIT_FAILURE"
export const SUBMIT_STARTED = "SUBMIT_STARTED"

export const FETCH_ORDER_INIT = "FETCH_ORDER_INIT"
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS"
export const FETCH_ORDER_FAIL = "FETCH_ORDER_FAIL"

   // Auth
export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAILURE = "AUTH_FAILURE"

  // Log out
export const AUTH_LOGOUT = "AUTH_LOGOUT"