// Altering Internally
export const ADD_INGREDIENT = "ADD_INGREDIENT"
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT"

// From Database
export const INIT_INGREDIENTS  = "INIT_INGREDIENTS"
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED"