// Altering Internally
export const ADD_INGREDIENT = "ADD_INGREDIENT"
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT"

// From Database
   // BURGER BUILDER
export const INIT_INGREDIENTS  = "INIT_INGREDIENTS"
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED"
   // ORDER SUBMIT
export const SUBMIT_START = "SUBMIT_START"
export const SUBMIT_SUCCESS = "SUBMIT_SUCCESS"
export const SUBMIT_FAILURE = "SUBMIT_FAILURE"